name: SW-Mileage-Manager-Front Deploy ( executing script )
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: login to walab server & execute script ( deploy )
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SW_MILEAGE_SSH_HOST }}
          username: ${{ secrets.SW_MILEAGE_SSH_USERNAME }}
          key: ${{ secrets.SW_MILEAGE_SSH_PASSWORD }}
          port: 22
          script: |
            whoami
            cd ~/sh-script/manager
            chmod 750 front-manager-script.sh
            ./front-manager-script.sh
